# Generated by Django 3.2 on 2023-02-18 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_empresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.sucursal'),
        ),
    ]
