# Generated by Django 3.2 on 2023-02-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20230219_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='numero_atencion',
            field=models.BigIntegerField(null=True),
        ),
    ]
