# Generated by Django 3.2 on 2023-02-20 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
        ('gestion', '0007_atencion_numero_atencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordatorio',
            name='id_sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.sucursal'),
        ),
    ]
