# Generated by Django 3.2 on 2024-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_metodopago_id_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
