# Generated by Django 3.2 on 2023-02-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ventas', '__first__'),
        ('productos', '__first__'),
        ('gestion', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.IntegerField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=7)),
                ('numero', models.IntegerField()),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento_proveedor', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=150)),
                ('telefono_proveedor', models.CharField(blank=True, max_length=9, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=9, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.tipodocumento')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detalle_compra', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('id_compra', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compras.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalle de Compras',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compras.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.sucursal'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_tipo_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.tipocomprobante'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
