# Generated by Django 3.2 on 2023-09-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_proveedor_id_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha_registro',
            field=models.DateField(null=True),
        ),
    ]
