# Generated by Django 3.2 on 2023-02-18 12:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '__first__'),
        ('gestion', '0001_initial'),
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parametro',
                'verbose_name_plural': 'Parametros',
            },
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id_tipo_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Comprobante',
                'verbose_name_plural': 'Tipos de Comprobantes',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=4)),
                ('numero', models.IntegerField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operacion_gravada', models.DecimalField(decimal_places=2, max_digits=8)),
                ('porcentaje_igv', models.DecimalField(decimal_places=2, max_digits=6)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('estado', models.IntegerField(choices=[(0, 'Anulada'), (1, 'Realizada')])),
                ('motivo_anulacion', models.TextField(blank=True, max_length=100, null=True)),
                ('id_usuario_anulador', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.cliente')),
                ('id_metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestion.metodopago')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empresa.sucursal')),
                ('id_tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.tipocomprobante')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productos.producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
            },
        ),
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id_correlativo', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=4)),
                ('primer_numero', models.IntegerField()),
                ('ultimo_numero_registrado', models.PositiveBigIntegerField(blank=True, null=True)),
                ('max_correlativo', models.PositiveBigIntegerField()),
                ('id_tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ventas.tipocomprobante')),
            ],
            options={
                'verbose_name': 'Correlativo',
                'verbose_name_plural': 'Correlativos',
            },
        ),
    ]
