# Generated by Django 3.2 on 2023-02-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('ventas', '0002_correlativo_id_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_producto_sucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.productosucursal'),
            preserve_default=False,
        ),
    ]
