# Generated by Django 3.2 on 2023-02-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('ventas', '0003_auto_20230226_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='id_producto_sucursal',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='productos.producto'),
            preserve_default=False,
        ),
    ]
