# Generated by Django 3.2 on 2023-03-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='token_correo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
