# Generated by Django 3.2 on 2023-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20230304_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado_pago',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
