# Generated by Django 3.2 on 2023-03-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_empresa_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='estado_pago',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
